spring.application.name=order
server.port=8085

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=order_db

services.product.url=http://localhost:8081
services.user.url=http://localhost:8082
services.inventory.url=http://localhost:8083
services.payment.url=http://localhost:8084